import { BrainTypeEnum } from "../models/brain.model";
import { IConfig } from "../models/config.model";
import { DEFAULT_OLLAMA_HOST, DEFAULT_OLLAMA_MODEL } from "../models/ollama.model";

export const INIT_EXAMPLE_CONFIG:IConfig = {
    projectPath: "./your-project",
    outputDir: "./handover-docs",
    llmProvider: BrainTypeEnum.Ollama,
    llmBaseUrl: DEFAULT_OLLAMA_HOST,
    llmModel: DEFAULT_OLLAMA_MODEL,
    llmKey: undefined,
    projectName: "My Project",
    exclude: [
        "node_modules/**",
        "dist/**",
        "build/**",
        "coverage/**",
        ".git/**",
        ".vscode/**",
        ".idea/**",
        "**/*.test.ts",
        "**/*.spec.ts",
        "**/*.test.js",
        "**/*.spec.js",
        "**/__tests__/**",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        ".env",
        ".env.*",
        "**/*.log",
        "handover-docs/**",
    ],
    include: [
        "**/*.ts",
        "**/*.tsx",
        "**/*.js",
        "**/*.jsx",
        "**/*.mts",
        "**/*.cts",
        "**/*.mjs",
        "**/*.cjs",
        "**/*.json",
        "**/*.md",
    ],
    generateHtml: true,
    generateMarkdown: true,
    languageDoc: "english",
    languages: ["typescript", "javascript"],
    analysisDepth: "detailed",
}